# Generated by Django 5.2 on 2025-10-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_director_movie_stroy_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stroy',
            new_name='story',
        ),
    ]
